### ISSUE TITLE
Create a GitHub issue template for users

### ISSUE THREAD

**Issue by arianesasso** [hpi-dhc/devicely#32]
Request by @djmitche on https://github.com/openjournals/joss-reviews/issues/3679

"Just one request: something that helps users figure out how to report a bug and what level of support they can expect. This may just be a GitHub issue template, for example."

**Comment by jostmorgenstern** [comment]
I created two templates, one for bug reports and one for feature requests. They are very similar to the default templates.
Could you check if they are what you had in mind?

**Comment by djmitche** [comment]
Looks great -- thanks!
