### ISSUE TITLE
Suggestions for JOSS article text improvements

### ISSUE THREAD

**Issue by luciorq** [hpi-dhc/devicely#38]
Suggestions for [`inst/paper.md`](https://github.com/hpi-dhc/devicely/blob/be8dca604616edfd4e7d7a69a2eb11f776edb2bd/inst/paper.md)

- Line 52, reword "intended to help users a step before [...]" to "intended to help users in a prior step [...]"

https://github.com/hpi-dhc/devicely/blob/be8dca604616edfd4e7d7a69a2eb11f776edb2bd/inst/paper.md#L52

- Line 57, use _CSV_ instead of _csv_. Also use _Python_, instead of _python_.

https://github.com/hpi-dhc/devicely/blob/be8dca604616edfd4e7d7a69a2eb11f776edb2bd/inst/paper.md#L57

- Lines 60 and 61, reword "[...] also be used as a second step [...]" to "[...] also be used as a following step [...]" or "[...] also be used in a later step [...]"

https://github.com/hpi-dhc/devicely/blob/be8dca604616edfd4e7d7a69a2eb11f776edb2bd/inst/paper.md#L60-L61

- Line 75, _company_ can be replaced with _vendor_ for clarity.

https://github.com/hpi-dhc/devicely/blob/be8dca604616edfd4e7d7a69a2eb11f776edb2bd/inst/paper.md#L75

- Line 86, reword "Different wearables come with different data formats which require different [...]" to "Different wearables _provide incompatible_ data formats which require _specific_ [...]"

https://github.com/hpi-dhc/devicely/blob/be8dca604616edfd4e7d7a69a2eb11f776edb2bd/inst/paper.md#L86

**Comment by arianesasso** [comment]
Thank you @luciorq, all great suggestions :). I am incorporating them to the manuscript.

**Comment by luciorq** [comment]
LGTM
