### ISSUE TITLE
JOSS Paper - Avoid use of "patient"

### ISSUE THREAD

**Issue by luciorq** [hpi-dhc/devicely#39]
The use of the term "patient" can be misleading, as not always the device will be deployed in any medical setting or treatment.

In lines 39, 81, and 96 of [`inst/paper.md`](https://github.com/hpi-dhc/devicely/blob/be8dca604616edfd4e7d7a69a2eb11f776edb2bd/inst/paper.md) the term "patient" should be replaced.

https://github.com/hpi-dhc/devicely/blob/be8dca604616edfd4e7d7a69a2eb11f776edb2bd/inst/paper.md#L39

https://github.com/hpi-dhc/devicely/blob/be8dca604616edfd4e7d7a69a2eb11f776edb2bd/inst/paper.md#L81

https://github.com/hpi-dhc/devicely/blob/be8dca604616edfd4e7d7a69a2eb11f776edb2bd/inst/paper.md#L96

Suggestion to replace: **User, wearer, (?)**

Moreover, I would argue that the benefits of privacy extend far beyond patient care privacy and trust.
Therefore, a general tool that respects privacy should be the default for wearable devices collecting biometric data.

**Comment by arianesasso** [comment]
Changed to user 👍🏼

**Comment by luciorq** [comment]
LGTM
