### ISSUE TITLE
Spacelabs Reader Reading Empty Lines

### ISSUE THREAD

**Issue by arianesasso** [hpi-dhc/devicely#4]
SpaceLabs reader still reading lines with "empty" values, e. g.

date, time, 19, 1
date, time, 19, 1
date, time, 19, 1
date, time, 19, 1
date, time, 19, 1

**Comment by jostmorgenstern** [comment]
What columns have to present in a line for it to be valid? And should an empty string be treated the same way as an empty field?

**Comment by arianesasso** [comment]
Hey, so, your idea of creating a method remove_invalid makes sense, invalid would be diastolic values (4th column) less than < 20 for now 👍🏼 .
