### ISSUE TITLE
JOSS Paper - Figure 1 legend formatting and cross-reference

### ISSUE THREAD

**Issue by luciorq** [hpi-dhc/devicely#40]
Figure 1 has a double legend anchor "Figure 1" in the PDF version.

![Snippet from compiled PDF](https://user-images.githubusercontent.com/22479186/132426002-26e9423d-1a15-460c-b3be-db4e9647cc30.png)

Remove the text "Figure 1" from `inst/paper.md` markdown file, line 115.

It is not necessary to write "Figure X".
Pandoc automatically adds figure numbers.

https://github.com/hpi-dhc/devicely/blob/be8dca604616edfd4e7d7a69a2eb11f776edb2bd/inst/paper.md#L115

---

Following this topic, it is also considered good practice to not hard code figure numbers in the text,
the reference syntax (\label{fig:figname} and \autoref{fig:figname}) can be used to avoid that,
and also provide a clickable figure reference in the text.

E.g.:

```markdown
# Figures

Figures can be included like this:

![Caption for example figure.\label{fig:example}](figure.png)

and referenced from text using \autoref{fig:example}.
```

**Comment by arianesasso** [comment]
Thanks for the tip!

**Comment by luciorq** [comment]
LGTM
