### ISSUE TITLE
JOSS Paper - Figure 1 legend text improvement

### ISSUE THREAD

**Issue by luciorq** [hpi-dhc/devicely#41]
In Figure 1, line 115 ([`inst/paper.md`](https://github.com/hpi-dhc/devicely/blob/be8dca604616edfd4e7d7a69a2eb11f776edb2bd/inst/paper.md)) the legend is poorly written.
Figure legends should be self-contained and provide a descriptive summary of what is being shown.

https://github.com/hpi-dhc/devicely/blob/be8dca604616edfd4e7d7a69a2eb11f776edb2bd/inst/paper.md#L115

**Comment by arianesasso** [comment]
Thanks, I think you were completely right :). Let me know if that is good enough!

Cheers
Ariane

**Comment by luciorq** [comment]
LGTM
