### ISSUE TITLE
JOSS Paper - Copyright and Governance model

### ISSUE THREAD

**Issue by luciorq** [hpi-dhc/devicely#43]
Regarding Copyright

Your institution is regarded as the copyright holder for the `devicely` software package, including documentation and source code.

Does your institution (or organization) have any public documents about the specific requirements for software products as part of Staff work or research outcome?
E.g. specific licensing requirements for intellectual property derived from the software.

Can you provide additional information on your institution's policies regarding software and open-source,
including how your institution would treat public commits made by contributors outside of the institution, outside of formal collaborators, and contractors.

In which case, could be useful to create a Contributing Guideline, stating that everyone needs to give up ownership of their intellectual property when contributing to `devicely` development.

**Comment by arianesasso** [comment]
Dear @luciorq, I was looking for that but at this moment my institution does not have a specific public policy on open-source. That is why we decided to leave the copyright like that. There is some requirements in our contracts but they are not extensive and only apply to employees of the institution.

I believe the package maintainers are encouraged to make this decisions at this moment in time. 

We have a contributing guideline here: https://hpi-dhc.github.io/devicely/contribution.html. I will add that extra information there.

Thank you for pointing that out!

**Comment by arianesasso** [comment]
Updated: https://hpi-dhc.github.io/devicely/contribution.html#license-and-copyright

**Comment by luciorq** [comment]
Great, the documentation website is well written and contemplates the necessary information.

Closing
