### ISSUE TITLE
JOSS Paper - Availability section - PyPI

### ISSUE THREAD

**Issue by luciorq** [hpi-dhc/devicely#44]
In the 'Availability' section of [`inst/paper.md`](https://github.com/hpi-dhc/devicely/blob/a04dfbc687f6ce66b77dbcde727f1d856ab09d0a/inst/paper.md).

https://github.com/hpi-dhc/devicely/blob/a04dfbc687f6ce66b77dbcde727f1d856ab09d0a/inst/paper.md#L118-L121

_pip_ is just the package installer, it would be better to address the software repository, the correct reference would be to the Python Package Index (PyPI).

It would also be good to include the link to the PyPI website or reference (https://pypi.org/project/devicely).

**Comment by arianesasso** [comment]
Done, and also added the reference to conda-forge.

**Comment by luciorq** [comment]
Closing
