### ISSUE TITLE
JOSS Paper - Availability section - Zenodo

### ISSUE THREAD

**Issue by luciorq** [hpi-dhc/devicely#45]
In the 'Availability' section of [`inst/paper.md`](https://github.com/hpi-dhc/devicely/blob/a04dfbc687f6ce66b77dbcde727f1d856ab09d0a/inst/paper.md).

https://github.com/hpi-dhc/devicely/blob/a04dfbc687f6ce66b77dbcde727f1d856ab09d0a/inst/paper.md#L118-L121

Including the [Zenodo](https://zenodo.org/) archive in the 'Availability' section would be good. Also stating the correct URL to the deposit <https://zenodo.org/record/5243494>

**Comment by arianesasso** [comment]
Also done :).

**Comment by luciorq** [comment]
Closing #44 and #45.

The availability section is clearer now.
