### ISSUE TITLE
Automation, CI & CD suggestions

### ISSUE THREAD

**Issue by luciorq** [hpi-dhc/devicely#48]
As the project is already using GitHub Actions for automated tests and coverage, it can greatly reduce the maintenance burden to integrate some more workflows.

As you have large documentation you should provide some automation workflow for documentation being regenerated at each commit or Pull Request, so contributors don't need to regenerate it before a Pull Request, also guaranteeing that the state of the documentation always follows the state of the code itself.

You can also set workflows to automatically releasing the package to PyPI or Zenodo, based on a GitHub Release.

**Comment by luciorq** [comment]
Documentation automation was already addressed in the past but got removed. There was any specific limitation for the sphinx GH action?

**Comment by arianesasso** [comment]
@jostmorgenstern I think you are the best to answer this question :).

**Comment by jostmorgenstern** [comment]
@luciorq Thank you for your suggestions!
We created workflows for pushing to PyPi and rendering the docs on GH pages, both triggered on releases.
This way, the PyPi package and the documentation always refer to the same package version.
Also it automates a large part of our deployment workflow.

**Comment by luciorq** [comment]
@jostmorgenstern Great, future contributors (and also your future self) will be pleased by the automation.

Closing #48
