### ISSUE TITLE
JOSS Paper - use of 'dataframe' as user-friendly

### ISSUE THREAD

**Issue by luciorq** [hpi-dhc/devicely#49]
[`inst/paper.md`](https://github.com/hpi-dhc/devicely/blob/a04dfbc687f6ce66b77dbcde727f1d856ab09d0a/inst/paper.md) - Lines 90 and 102 - dataframe

https://github.com/hpi-dhc/devicely/blob/a04dfbc687f6ce66b77dbcde727f1d856ab09d0a/inst/paper.md#L90

https://github.com/hpi-dhc/devicely/blob/a04dfbc687f6ce66b77dbcde727f1d856ab09d0a/inst/paper.md#L102

[`README.md`](https://github.com/hpi-dhc/devicely/blob/2bd30962be35e1beaccfae1225fd15ecbca7bde4/README.md) - Line 14 - dataframe

https://github.com/hpi-dhc/devicely/blob/2bd30962be35e1beaccfae1225fd15ecbca7bde4/README.md#L14

'dataframe' is not a native Python data structure.
It is actually a _lingo_ that is not that clear for non-developer users.

It can also mean different data structures depending on tools, languages, and context.

In the text, it is also addressed that `devicely` output is in a _science-friendly_ format, but it is not clearly defined what this format is.

As you point that your Software is aimed at scientists, I would suggest being more specific about the kind of structure/files available as output.

I can suggest using _columnar format_, _rectangular format_, _tabular format_ or just _table_(?), instead of 'dataframe'.

If stating specificities of dealing with Pandas DataFrames, it would also be good to write as DataFrame or Pandas DataFrame.

**Comment by arianesasso** [comment]
Very good point indeed. I changed `science-friendly format` to `tabular` format and the other references to `dataframes` to `Pandas DataFrames`.

**Comment by luciorq** [comment]
LGTM. Closing.
