### ISSUE TITLE
Unify description in different Repositories and Archives

### ISSUE THREAD

**Issue by luciorq** [hpi-dhc/devicely#50]
As software evolves it is normal to change the documentation, description, and branding.

It would be good to have a central source of Title, Description, and general metadata to reduce the need of manually editing several repositories and files.

It is recommended to use the same title and description (also the author list, if relevant) for all the associated repositories.

Currently, I could observe different description metadata on the following files and places: `pyproject.toml`, GitHub Repo, `ìnst/paper.md`, PyPI, and Zenodo metadata.

The [CodeMeta Project](https://codemeta.github.io/) does a great job on aggregating language-independent metadata, but since you are already using `poetry`, I would suggest using the `poetry` configuration file as the central source of metadata.

Relevant files:

- [`pyproject.toml`](https://github.com/hpi-dhc/devicely/blob/a04dfbc687f6ce66b77dbcde727f1d856ab09d0a/pyproject.toml) - Line 4

https://github.com/hpi-dhc/devicely/blob/a04dfbc687f6ce66b77dbcde727f1d856ab09d0a/pyproject.toml#L4

---

- [`inst/paper.md`](https://github.com/hpi-dhc/devicely/blob/2bd30962be35e1beaccfae1225fd15ecbca7bde4/README.md)

https://github.com/hpi-dhc/devicely/blob/a04dfbc687f6ce66b77dbcde727f1d856ab09d0a/inst/paper.md#L2

---

- [GitHub Repo](https://github.com/hpi-dhc/devicely) Description

![Devicely GitHub repo description](https://user-images.githubusercontent.com/22479186/132511476-061ae0b2-f7af-409d-b55b-290a63848af3.png)

---

- [PyPI Description](https://pypi.org/project/devicely/)

![Devicely PyPi description](https://user-images.githubusercontent.com/22479186/132512143-94f8c1dd-d9eb-46a2-b701-60f972b8b194.png)

---

- [Zenodo metadata](https://zenodo.org/record/5243494/export/json)

**Comment by arianesasso** [comment]
I think I have covered that, thanks for noticing. Just PyPi needs to be updated with the next version of devicely. And for Zenodo, I think you mean the authors' names right? If that is the case, I have made the change as well.

**Comment by luciorq** [comment]
@arianesasso Yes, it was mostly about divergent information on Zenodo and PyPI. Especially because the Zenodo archive is supposed to be a permanent snapshot of your software at this time point, including its documentation, manuscript, and metadata.

**Comment by luciorq** [comment]
Closing
